import type { StyleSpecification } from "maplibre-gl";
import { layers, namedFlavor } from "@protomaps/basemaps";

/**
 * MapLibre style for the offline packs: the COMPLETE Protomaps "light"
 * flavor generated by @protomaps/basemaps for the archives' schema (v4),
 * not a hand-pruned subset — full street/place/water/park/POI label set.
 *
 * Two local adjustments, applied structurally (never by deleting layers):
 *  - Every label size is scaled up 15% with a 12px floor — the app's
 *    readers skew 60+, and 10px street names fail outdoors in sunlight.
 *  - Minor-road labels start at z14 (the flavor defaults to z15); our
 *    audit proved names exist in the data from z14, and travelers on foot
 *    live at z14-z16.
 *
 * All render assets are self-hosted (offline is a guarantee, so the style
 * contains no remote URLs): glyphs for every range of every stack under
 * /map-fonts, the light sprite under /map-sprites (both fetched by
 * scripts/fetch-map-assets.mjs). Attribution is plain text on purpose —
 * links are useless with no connection.
 */

const LABEL_SCALE = 1.15;
const MIN_LABEL_PX = 12;

function scaleNumber(n: number): number {
  return Math.max(MIN_LABEL_PX, Math.round(n * LABEL_SCALE * 10) / 10);
}

/**
 * Scales the numeric outputs of a text-size value without disturbing
 * expression structure. Zoom-driven sizes must keep `zoom` in a top-level
 * interpolate/step, so wrapping the whole expression in ["*", …] is not an
 * option — the outputs are scaled in place instead.
 */
function scaleTextSize(value: unknown): unknown {
  if (typeof value === "number") return scaleNumber(value);
  if (!Array.isArray(value)) return value;

  const op = value[0];
  const out = [...value] as unknown[];
  if (op === "interpolate") {
    // ["interpolate", interp, input, stop1, out1, stop2, out2, …]
    for (let i = 4; i < out.length; i += 2) out[i] = scaleTextSize(out[i]);
  } else if (op === "step") {
    // ["step", input, out0, stop1, out1, …]
    for (let i = 2; i < out.length; i += 2) out[i] = scaleTextSize(out[i]);
  } else if (op === "case") {
    // ["case", cond1, out1, …, fallback]
    for (let i = 2; i < out.length - 1; i += 2) out[i] = scaleTextSize(out[i]);
    out[out.length - 1] = scaleTextSize(out[out.length - 1]);
  } else if (op === "match") {
    // ["match", input, label1, out1, …, fallback]
    for (let i = 3; i < out.length - 1; i += 2) out[i] = scaleTextSize(out[i]);
    out[out.length - 1] = scaleTextSize(out[out.length - 1]);
  } else if (op === "coalesce") {
    for (let i = 1; i < out.length; i += 1) out[i] = scaleTextSize(out[i]);
  }
  return out;
}

export function buildMapStyle(opts: {
  /** pmtiles protocol key for the active pack, e.g. "florence" */
  key: string;
  /** [minLon, minLat, maxLon, maxLat] of the pack */
  bounds: [number, number, number, number];
  /** Data maxzoom of the archive — MapLibre overzooms beyond it. */
  maxzoom: number;
}): StyleSpecification {
  const flavor = namedFlavor("light");
  const styleLayers = layers("basemap", flavor, { lang: "en" });

  for (const layer of styleLayers) {
    if (layer.type !== "symbol" || !layer.layout) continue;
    const layout = layer.layout as Record<string, unknown>;
    if (layout["text-size"] !== undefined) {
      layout["text-size"] = scaleTextSize(layout["text-size"]);
    }
    if (layer.id === "roads_labels_minor") layer.minzoom = 14;
  }

  return {
    version: 8,
    glyphs: "/map-fonts/{fontstack}/{range}.pbf",
    // Unlike glyphs, MapLibre requires an absolute sprite URL — a relative
    // one is silently ignored and every icon layer logs a missing-image
    // warning. buildMapStyle only runs client-side (MapView is ssr:false).
    sprite: new URL("/map-sprites/light", window.location.href).href,
    sources: {
      basemap: {
        type: "vector",
        // Tile scheme + metadata declared inline (from the generated pack
        // manifest) so the style needs no TileJSON round trip.
        tiles: [`pmtiles://${opts.key}/{z}/{x}/{y}`],
        bounds: opts.bounds,
        minzoom: 0,
        maxzoom: opts.maxzoom,
        attribution: "© OpenStreetMap · Protomaps",
      },
    },
    layers: styleLayers,
  };
}

/**
 * Cartography colors for the DOM safety markers (lib/mapMarkers.ts).
 * Raw hex is sanctioned in this file only (canvas cartography); marker
 * colors are wayfinding identities, not UI tokens. None is signal red —
 * markers are wayfinding, never emergency actions.
 */
export const MARKER_COLORS = {
  /** Italian hospital road-sign blue — the exact sign on the street. */
  er: "#1B62B5",
  /** Navy pin for embassies & consulates. */
  embassy: "#1D3557",
  /** Police dark blue — distinct from hospital blue by shape AND tone. */
  police: "#27408B",
} as const;
