/**
 * Generated by scripts/build-map-packs.mjs — do not edit by hand.
 * Protomaps build 20260723. Regenerate after changing bounding boxes or
 * shipping new packs. Every pack is verified (magic bytes, size caps).
 */
export type MapPack = {
  id: string;
  name: string;
  nameIt: string;
  /** [minLon, minLat, maxLon, maxLat] */
  bbox: [number, number, number, number];
  /** [lng, lat] */
  center: [number, number];
  /** Max tile zoom baked into the archive. */
  maxzoom: number;
  sizeBytes: number;
};

export const MAP_PACKS: MapPack[] = [
  {
    "id": "rome",
    "name": "Rome",
    "nameIt": "Roma",
    "bbox": [
      12.17,
      41.65,
      12.73,
      42.05
    ],
    "center": [
      12.4964,
      41.9028
    ],
    "maxzoom": 14,
    "sizeBytes": 20548707
  },
  {
    "id": "tuscany",
    "name": "Tuscany",
    "nameIt": "Toscana",
    "bbox": [
      10.25,
      42.95,
      12.1,
      43.95
    ],
    "center": [
      11.2558,
      43.7696
    ],
    "maxzoom": 13,
    "sizeBytes": 40351062
  }
];
