/**
 * Generated by scripts/build-map-packs.mjs — do not edit by hand.
 * Protomaps build 20260722, maxzoom 14. Regenerate after changing
 * bounding boxes or shipping new cities.
 */
export type MapPack = {
  id: string;
  name: string;
  nameIt: string;
  /** [minLon, minLat, maxLon, maxLat] */
  bbox: [number, number, number, number];
  /** [lng, lat] */
  center: [number, number];
  sizeBytes: number;
};

export const PACKS_MAXZOOM = 14;

export const MAP_PACKS: MapPack[] = [
  {
    "id": "rome",
    "name": "Rome",
    "nameIt": "Roma",
    "bbox": [
      12.17,
      41.65,
      12.73,
      42.05
    ],
    "center": [
      12.4964,
      41.9028
    ],
    "sizeBytes": 20545198
  },
  {
    "id": "florence",
    "name": "Florence",
    "nameIt": "Firenze",
    "bbox": [
      11.1,
      43.7,
      11.4,
      43.85
    ],
    "center": [
      11.2558,
      43.7696
    ],
    "sizeBytes": 7643161
  },
  {
    "id": "venice",
    "name": "Venice",
    "nameIt": "Venezia",
    "bbox": [
      12.15,
      45.37,
      12.5,
      45.55
    ],
    "center": [
      12.3155,
      45.4408
    ],
    "sizeBytes": 5734379
  },
  {
    "id": "milan",
    "name": "Milan",
    "nameIt": "Milano",
    "bbox": [
      9.02,
      45.35,
      9.35,
      45.58
    ],
    "center": [
      9.19,
      45.4642
    ],
    "sizeBytes": 13027146
  },
  {
    "id": "naples",
    "name": "Naples",
    "nameIt": "Napoli",
    "bbox": [
      14.1,
      40.78,
      14.4,
      40.95
    ],
    "center": [
      14.2681,
      40.8518
    ],
    "sizeBytes": 7447578
  }
];
